#!/bin/perl



# perl ConvertMPR_to_MDT 1.3.1.6.mpr   /tmp/1.3.1.6_XYZ_RandomNumber  /tmp/DocFile_XYZ_RandomNumber





@numbers = ();
@NeededLines = () ;


$filename     = $ARGV[0] ;
$Out_filename = $ARGV[1] ;
$doc_filename = $ARGV[2] ;

if (! open(FILENAME,$filename))  {
        die " ***** Could not open $filename \n\n";
        }


open F, "> $Out_filename" or die "Can't open $Out_filename : $!";



while (<FILENAME>) {

        $line = $_ ;
        chop ($line);

	if ($line =~ / out/) {
		$from = $` ;
		$from =~ s/://g; 
		# print "Idrees from=$from=\n";
	}

	elsif ($line =~ / to /) {
		$to = $' ;   $msg=$`;
		$to =~ s/;//g;
		# print "Idrees to=$to=\n";

		# Orig $msg =~ s/,\d+//g;
		# Orig $msg =~ s/\(|\)|,/ /g;
		$msg =~ s/,\d+\(/    /g;
		$msg =~ s/\) / /g;

		# print "Idrees msg=$msg=\n";

		printf (F  "%-20.20s %-20.20s   %s\n",$from,$to,$msg);
		# printf ("%-20.20s %-20.20s   %s\n",$from,$to,$msg);
	

	}

	

}

close (FILENAME);
close (F);


&CreateDocFile();







sub CreateDocFile
{

        if (! open(FILENAME,$filename))  { die " ***** Could not open $filename \n\n"; }

        @DocLines = () ;
        $cont = 0 ;
        while (<FILENAME>) {

                $line =$_;
                if ($line =~ /text/) { $cont = 1 ;}

                if ($cont) {
                        push (@DocLines,$line) ;
                        if ($line =~ /';/) {last ;}
                }
        }
        close(FILENAME);





        open DF, "> $doc_filename " or die "Can't open $doc_filename : $!";
        print DF "@DocLines";
        close (DF) ;

}




